apiVersion: v1
kind: ServiceAccount
metadata:
  name: cyclops
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cyclops
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - get
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
  - patch
  - watch
  - list
  - get
  - delete
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - deployments
  - controllerrevisions
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - atlassian.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cyclops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cyclops
subjects:
- kind: ServiceAccount
  name: cyclops
  namespace: kube-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cyclops
  namespace: kube-system
rules:
# For leader election
- apiGroups:
  - ""
  resourceNames:
  - cyclops-lock
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cyclops
  namespace: kube-system
roleRef:
  kind: Role
  name: cyclops
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cyclops
  namespace: kube-system
