apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyclops
      role: cyclops
  template:
    metadata:
      labels:
        app: cyclops
        role: cyclops
    spec:
      serviceAccountName: cyclops
      containers:
        - name: cyclops
          image: atlassian/cyclops:latest
          command:
          - cyclops
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: AWS_REGION
            value: us-east-1
          # Required for leader election
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: cyclops
    app: cyclops
  name: cyclops
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    role: cyclops